### ISSUE TITLE
Error starting function

### ISSUE THREAD

**Issue by Jey0707** [CheshireCaat/bas-remote-python#1] opened 2022-05-26 10:15 UTC
File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Farella Vito\Desktop\Test\main.py", line 15, in main
    await script_client.start()
  File "C:\Python310\lib\site-packages\bas_remote\client.py", line 60, in start
    await self._engine.start(port)
  File "C:\Python310\lib\site-packages\bas_remote\services\engine_service.py", line 61, in start
    self._start_engine_process(port)
  File "C:\Python310\lib\site-packages\bas_remote\services\engine_service.py", line 102, in _start_engine_process
    self._process = subprocess.Popen([
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000221F549FD90>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by Jey0707** [comment] 2022-05-26 10:40
File "C:\Python310\lib\site-packages\bas_remote\services\engine_service.py", line 99, in _extract_executable
    await asyncio.wait(tasks, loop=self._loop)
TypeError: wait() got an unexpected keyword argument 'loop'
sys:1: RuntimeWarning: coroutine 'EngineService._extract_executable.<locals>.task' was never awaited

First run ^

**Comment by CheshireCaat** [comment] 2022-05-26 11:07
This package requires a python version higher than or equal to 3.7

**Comment by Jey0707** [comment] 2022-05-26 11:09
Yes, I'm using Python 3.10.1

**Comment by CheshireCaat** [comment] 2022-05-26 11:51
@VitoFarella, OK, sorry, I misread the version. Apparently, in versions above 3.8 there are breaking changes related to `asyncio`. I'll try to come up with something when I have time. For now, you can safely use it on versions 3.7 - 3.8.

**Comment by CheshireCaat** [comment] 2022-05-26 16:17
@VitoFarella try version 1.2. If everything works correctly, please close the issue.

**Comment by Jey0707** [comment] 2022-05-26 17:47
No problem!
 
 Now after upgrade I have this error:
 
 File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Farella Vito\Desktop\Nuova cartella\main.py", line 11, in main
    await client.start()
  File "C:\Python310\lib\site-packages\bas_remote\client.py", line 61, in start
    await self._socket.start(port)
  File "C:\Python310\lib\site-packages\bas_remote\services\socket_service.py", line 36, in start
    self._socket = await connect(f'ws://127.0.0.1:{port}')
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "C:\Python310\lib\asyncio\base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Python310\lib\asyncio\base_events.py", line 1098, in _create_connection_transport
    protocol = protocol_factory()
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "C:\Python310\lib\site-packages\websockets\legacy\protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
  File "C:\Python310\lib\asyncio\locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "C:\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary


^first run

**Comment by CheshireCaat** [comment] 2022-05-26 18:20
@VitoFarella, right now I can't reproduce this problem using Python `3.10.4` and virtual environment. Please show your code (upload it to the sandbox or pastebin), try using a virtual environment if you're not already using it.

**Comment by Jey0707** [comment] 2022-05-26 18:22
https://pastebin.com/qCU4ma2d

My code

**Comment by CheshireCaat** [comment] 2022-05-26 18:27
Can't repeat the error, everything works correctly. Try reinstalling the package and dependencies, use a virtual environment.

**Comment by Jey0707** [comment] 2022-05-26 18:30
I have tryied to reinstalling all, also updating python but I have always same error

**Comment by Jey0707** [comment] 2022-05-26 18:39
I have also this error while running for second time:
```

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\bas_remote\services\socket_service.py", line 36, in start
    self._socket = await connect(f'ws://127.0.0.1:{port}')
  File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "C:\Python310\lib\asyncio\base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "C:\Python310\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "C:\Python310\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Python310\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Python310\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] Il computer remoto ha rifiutato la connessione di rete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Farella Vito\Desktop\Test2\main.py", line 21, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Farella Vito\Desktop\Test2\main.py", line 10, in main
    await client.start()
  File "C:\Python310\lib\site-packages\bas_remote\client.py", line 61, in start
    await self._socket.start(port)
  File "C:\Python310\lib\site-packages\bas_remote\services\socket_service.py", line 39, in start
    raise SocketNotConnectedError()
bas_remote.errors.SocketNotConnectedError
```

**Comment by CheshireCaat** [comment] 2022-05-26 18:51
> I have also this error while running for second time

Try remove the `data` directory.

**Closed as completed by CheshireCaat** 2022-05-26 18:51 UTC

**Comment by Jey0707** [comment] 2022-05-26 19:44
Removed, but when I retry after remove, i have this again

File "C:\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
return future.result()
File "C:\Users\Farella Vito\Desktop\Nuova cartella\main.py", line 11, in main
await client.start()
File "C:\Python310\lib\site-packages\bas_remote\client.py", line 61, in start
await self._socket.start(port)
File "C:\Python310\lib\site-packages\bas_remote\services\socket_service.py", line 36, in start
self._socket = await connect(f'ws://127.0.0.1:{port}')
File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 622, in await_impl
transport, protocol = await self._create_connection()
File "C:\Python310\lib\asyncio\base_events.py", line 1080, in create_connection
transport, protocol = await self._create_connection_transport(
File "C:\Python310\lib\asyncio\base_events.py", line 1098, in _create_connection_transport
protocol = protocol_factory()
File "C:\Python310\lib\site-packages\websockets\legacy\client.py", line 160, in init
super().init(**kwargs)
File "C:\Python310\lib\site-packages\websockets\legacy\protocol.py", line 154, in init
self._drain_lock = asyncio.Lock(
File "C:\Python310\lib\asyncio\locks.py", line 77, in init
super().init(loop=loop)
File "C:\Python310\lib\asyncio\mixins.py", line 17, in init
raise TypeError(
TypeError: As of 3.10, the loop parameter was removed from Lock() since it is no longer necessary

**Comment by CheshireCaat** [comment] 2022-05-26 20:27
Try version 1.3

**Comment by VitoFarella** [comment] 2022-05-26 22:49
Now I have no more precedent error, but when I start a script it go in infinite pending and then timeout.
I have tryed to see log files but they are empty

**Comment by Jey0707** [comment] 2022-05-26 23:43
With version 1.3 I have no more precedent errors but I have this new error:

result = await client.run_function('CheckIp')
bas_remote.errors.FunctionError: Timeout during creating new process

**Comment by Jey0707** [comment] 2022-05-29 00:19
Worked, antivirus was bloking BAS, thank you so much

**Comment by Jey0707** [comment] 2022-05-29 10:10
I have only a question:
when I tryed to start client in different function in a function other than the one where I start the bas function I got asyncio loop error.
I don’t understand how I could fix it, my idea was to start with only one client at the start of the application to reuse it when needed without creating a new one

**Comment by CheshireCaat** [comment] 2022-05-29 13:46
@VitoFarella, it's best to use single client instance per application, because otherwise there may even be problems with the operation of the library as a whole - race-conditions etc. If you need to have multiple clients, at least specify different working folders.

Working with multiple clients without additional configuration has not been tested and may lead to errors. Also, please create separate issues for each individual problem, and only if it directly concerns the library.
